language: crystal
services:
  - docker
before_install:
  - docker run -p 6379:6379 -d redis
  - nvm install 9
  - npm install shelljs got
script:
  - env REDIS_URL=redis://localhost:6379 crystal spec
  - crystal docs
after_success:
  - node .travis/trigger-dependant-builds.js
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
